image: docker:20.10.21

variables:
  SCALA_RUNNER: sbtscala/scala-sbt:openjdk-18.0.2.1_1.8.0_3.2.1

stages:
- compile
- test
- deploy

compile:
  stage: compile
  image: $SCALA_RUNNER
  script:
    - sbt Test/compile

core:
  stage: test
  image: $SCALA_RUNNER
  services:
    - name: timescale/timescaledb:2.8.1-pg14
      alias: timescale
  variables:
    JAVA_OPTS: "-Dblizzard.clientId=$BLIZZARD_API_CLIENTID -Dblizzard.secret=$BLIZZARD_API_SECRET"
    POSTGRES_DB: "postgres"
    POSTGRES_PASSWORD: "password"
  script:
    - sbt 'project core' test
  except:
    - stable
    - development
    - tags

deploy:
  stage: deploy
  image: $SCALA_RUNNER
  script:
    - sbt Docker/publish
  only:
    - tags