image: docker:20.10.21

variables:
  SCALA_RUNNER: registry.jmmckinney.net/jmckinney/ci-runner-sbt:0.1.0

stages:
- compile
- test
- deploy

compile:
  stage: compile
  image: $SCALA_RUNNER
  script:
    - sbt Test/compile

core:
  stage: test
  image: $SCALA_RUNNER
  services:
    - name: timescale/timescaledb:2.8.1-pg14
      alias: timescale
  variables:
    JAVA_OPTS: "-Dblizzard.clientId=$BLIZZARD_API_CLIENTID -Dblizzard.secret=$BLIZZARD_API_SECRET"
    POSTGRES_DB: "postgres"
    POSTGRES_PASSWORD: "password"
  script:
    - sbt 'project core' test
  except:
    - stable
    - development
    - tags

deploy:
  stage: deploy
  image: $SCALA_RUNNER
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sbt Docker/publish
  only:
    - tags